// Generated by scripts/images/import-batch.mjs (or `npm run images:index`).
// Do not edit by hand.
//
// Ids of the files sitting in public/images/showcase. A showcase slot whose id
// appears here renders the generated image; every other slot keeps showing its
// GPT Image 2 prompt card, so the pages stay complete while a batch is only
// partly filled in.
export const GENERATED_IMAGES: readonly string[] = [];
