// Generates src/patterns.generated.ts and catalog.json from patterns/*.json.
//
// Embedding the presets as one named `const` per pattern (instead of reading
// JSON at runtime) removes any node:fs dependency from library code, gives
// consumers compile-time `PatternSlug` types, and lets bundlers tree-shake the
// presets a consumer never imports. Run via `npm run codegen` (also part of
// `npm run build`).
//
// catalog.json is the same data reshaped for *readers* rather than bundlers:
// one entry per design with the metadata needed to pick one and configure it,
// minus the css-doodle source. It ships in the published tarball and is
// served by the site, so an AI coding assistant can search the designs by
// description instead of guessing slugs. See scripts/generate-llms.mjs at the
// repo root, which builds the site's llms.txt from it.
import { readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const packageRoot = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const patternsDir = path.join(packageRoot, 'patterns');
const outFile = path.join(packageRoot, 'src', 'patterns.generated.ts');
const catalogFile = path.join(packageRoot, 'catalog.json');

// ES reserved words that pass the lowercase-alphanumeric slug check, plus the
// generated module's own exports.
const RESERVED_SLUGS = new Set([
  'break', 'case', 'catch', 'class', 'const', 'continue', 'debugger',
  'default', 'delete', 'do', 'else', 'enum', 'export', 'extends', 'false',
  'finally', 'for', 'function', 'if', 'implements', 'import', 'in',
  'instanceof', 'interface', 'let', 'new', 'null', 'package', 'private',
  'protected', 'public', 'return', 'static', 'super', 'switch', 'this',
  'throw', 'true', 'try', 'typeof', 'var', 'void', 'while', 'with', 'yield',
  'await', 'patterns', 'ispatternslug',
]);

const fileNames = (await readdir(patternsDir))
  .filter((fileName) => fileName.endsWith('.json'))
  .sort();

const patterns = await Promise.all(
  fileNames.map(async (fileName) => {
    const definition = JSON.parse(
      await readFile(path.join(patternsDir, fileName), 'utf-8')
    );
    const slug = fileName.replace(/\.json$/, '');

    if (definition.slug !== slug) {
      throw new Error(
        `patterns/${fileName}: "slug" is "${definition.slug}" but must match the file name`
      );
    }
    if (!/^[a-z][a-z0-9]*$/.test(slug)) {
      throw new Error(
        `patterns/${fileName}: slug must be a lowercase alphanumeric identifier`
      );
    }
    // Each slug becomes `export const <slug>`, so reserved words (and the
    // module's own identifiers) would generate a syntax/duplicate error.
    if (RESERVED_SLUGS.has(slug)) {
      throw new Error(
        `patterns/${fileName}: slug "${slug}" is a reserved identifier and cannot be used`
      );
    }

    return definition;
  })
);

const header = `// AUTO-GENERATED by scripts/codegen.mjs from patterns/*.json — do not edit.
// Regenerate with \`npm run codegen\` (runs automatically as part of \`npm run build\`).
import type { PatternDefinition } from './core/types.js';
`;

const consts = patterns
  .map(
    (definition) =>
      `export const ${definition.slug}: PatternDefinition = ${JSON.stringify(
        definition,
        null,
        2
      )};`
  )
  .join('\n\n');

const record = `export const patterns = {
${patterns.map(({ slug }) => `  ${slug},`).join('\n')}
} as const;

export type PatternSlug = keyof typeof patterns;

export function isPatternSlug(value: string): value is PatternSlug {
  return Object.prototype.hasOwnProperty.call(patterns, value);
}
`;

await writeFile(outFile, `${header}\n${consts}\n\n${record}`);

console.log(
  `codegen: wrote ${patterns.length} patterns to ${path.relative(
    packageRoot,
    outFile
  )}`
);

// ---- catalog.json ----

// The fit a pattern defaults to when none is requested. This mirrors
// defaultFitMode()/hasGridOption() in src/core/sizing.ts — kept in sync by
// hand because codegen runs before tsc, so there's no compiled module to
// import. If the rule there changes, change it here too.
const defaultFit = (definition) =>
  definition.sizing?.default ??
  (definition.options?.some((option) => option.id === 'grid')
    ? 'grid'
    : 'cover');

// Options minus `replace`/`code` — those are css-doodle template plumbing, not
// something a consumer passes. What's left is the id to key `options` by, the
// control type, and the range of accepted values.
const catalogOption = (option) => ({
  id: option.id,
  label: option.displayName,
  type: option.type,
  default: option.default,
  ...(option.options ? { values: option.options } : {}),
  ...(option.min != null ? { min: option.min } : {}),
  ...(option.max != null ? { max: option.max } : {}),
  ...(option.step != null ? { step: option.step } : {}),
  // Present only on ToggleSwitch options, and only while the toggle is on.
  ...(option.svgExportNote ? { svgExportNote: option.svgExportNote } : {}),
});

const { version } = JSON.parse(
  await readFile(path.join(packageRoot, 'package.json'), 'utf-8')
);

const catalog = {
  package: 'tabbied',
  version,
  count: patterns.length,
  docs: 'https://tabbied.com/llms.txt',
  // Repeated once here rather than on all 222 entries.
  usage: {
    install: 'npm install tabbied',
    import: "import { <slug> } from 'tabbied/patterns';",
    react:
      "import { TabbiedPattern } from 'tabbied/react';\n<TabbiedPattern pattern={<slug>} height={320} />",
    core: "import { createPattern } from 'tabbied';",
  },
  designs: patterns.map((definition) => ({
    slug: definition.slug,
    name: definition.name,
    ...(definition.description ? { description: definition.description } : {}),
    palette: definition.palette ?? [],
    ...(definition.colors ? { colors: definition.colors } : {}),
    options: (definition.options ?? []).map(catalogOption),
    fit: {
      default: defaultFit(definition),
      ...(definition.sizing?.allowed
        ? { allowed: definition.sizing.allowed }
        : {}),
    },
    ...(definition.defaultAspectRatio
      ? { defaultAspectRatio: definition.defaultAspectRatio }
      : {}),
    svgExport: {
      // Absent means supported; only the conic-sweep designs opt out.
      supported: definition.svgExport !== false,
      ...(definition.svgExportNote ? { note: definition.svgExportNote } : {}),
    },
  })),
};

await writeFile(catalogFile, `${JSON.stringify(catalog, null, 2)}\n`);

console.log(
  `codegen: wrote catalog for ${patterns.length} designs to ${path.relative(
    packageRoot,
    catalogFile
  )}`
);
