// Batch 1 (gallery orders 57-96): css-doodle.com sample variations + originals.
// Each def: vars = host-level custom props (rolled once per cell), rule = body of --rule.
// Conventions verified against css-doodle 0.51: solid colors / transforms / offsets /
// border-radius / clip-path(same arity) / box-shadow / opacity all transition on reseed;
// gradients are kept static or hidden beneath transforms.

export const batch1 = [
  {
    name: 'Prisma',
    slug: 'prisma',
    order: 57,
    white: true,
    description:
      'A full-bleed mosaic of half-square triangles in deep indigo and jewel tones — every reseed melts each facet into its next orientation.',
    palette: ['#1A1B3A', '#3E8BFF', '#3EECFF', '#FF3D8B', '#D89FFF', '#3FFFB2'],
    colors: { min: 2, max: 6, default: 6 },
    gridDefault: '8x12',
    freqDefault: 1,
    thumb: { grid: '6x6', frequency: 0.92 },
    vars: `/* Triangle orientation and ink roll once per cell; same-arity polygons morph between seeds */ --tri: @p(polygon(0% 0%, 100% 0%, 100% 100%), polygon(0% 0%, 100% 0%, 0% 100%), polygon(0% 0%, 100% 100%, 0% 100%), polygon(100% 0%, 100% 100%, 0% 100%)); --ink: @p(var(--color1), var(--color1), var(--color2), var(--color3), var(--color4), var(--color5));`,
    rule: `margin: -0.5px; clip-path: var(--tri); @random(\${shapeFrequency}) { background: var(--ink); } transition: ease 500ms;`,
  },
  {
    name: 'Crescendo',
    slug: 'crescendo',
    order: 58,
    description:
      'The classic multiplication-table doodle with the numbers stripped away: tone deepens smoothly with row times column, re-rolling its grid on every redraw.',
    palette: ['#FFFFFF', '#60569E'],
    colors: { min: 2, max: 2, default: 2 },
    gridDefault: '8x12',
    options: [{ kind: 'grid', default: '8x12' }],
    thumb: { grid: '6x6' },
    vars: ``,
    rule: `margin: 0.5px; background: var(--color1); opacity: @calc(0.04 + 0.96 * sqrt((@x * @y) / (@X * @Y))); transition: ease 500ms;`,
  },
  {
    name: 'Circuit',
    slug: 'circuit',
    order: 60,
    description:
      'Random walls of hairline traces with bright component nodes soldered in between — the board rewires itself on every redraw.',
    palette: ['#F7F9F4', '#232529', '#FF3D8B', '#3E8BFF', '#3FFFB2', '#F5DD32'],
    colors: { min: 2, max: 6, default: 6 },
    gridDefault: '10x15',
    freqDefault: 0.6,
    thumb: { grid: '8x8', frequency: 0.6 },
    vars: `--node: @p(var(--color2), var(--color3), var(--color4), var(--color5)); --nx: @rand(18%, 66%); --ny: @rand(18%, 66%);`,
    rule: `margin: -0.5px; @random(\${shapeFrequency}) { border-top: 2px solid var(--color1); } @random(\${shapeFrequency}) { border-left: 2px solid var(--color1); } @random(0.16) { :after { content: ''; position: absolute; @size: 13%; left: var(--nx); top: var(--ny); background: var(--node); transition: ease 500ms; } } transition: ease 500ms;`,
  },
  {
    name: 'Daybreak',
    slug: 'daybreak',
    order: 61,
    description:
      'Rays of light fanning out of the top-left corner — every redraw sweeps the beams to new angles and lengths, like dawn through a window.',
    palette: ['#FCFBFF', '#60569E', '#9B8FD4', '#E6437D', '#3E8BFF', '#C9BFF2'],
    colors: { min: 2, max: 6, default: 6 },
    options: [
      {
        id: 'rays',
        displayName: 'Rays',
        type: 'Slider',
        default: 48,
        min: 24,
        max: 72,
        step: 8,
        replace: '${rays}',
      },
    ],
    doodle: `:doodle { @grid: 1x\${rays}; @size: \${width} \${height}; overflow:hidden; text-align:center; box-sizing:border-box } :container { background: var(--color0); overflow:hidden; }`,
    thumb: { options: { rays: 48 } },
    vars: `--ray: @p(var(--color1), var(--color1), var(--color2), var(--color3), var(--color4), var(--color5));`,
    rule: `@place-cell: 0 0; @size: 200% 1.5px; background: var(--ray); opacity: @rand(0.2, 1); transform: rotate(@rand(1deg, 89deg)) translateX(@rand(-12%, 25%)) scaleX(@rand(0.35, 1)); transition: ease 700ms;`,
  },
  {
    name: 'Quilt',
    slug: 'quilt',
    order: 68,
    description:
      'Half-square triangle patchwork in fabric tones — each block re-cuts its diagonal and trades patches on every redraw.',
    palette: ['#FBF3E4', '#D96C47', '#E3A92E', '#7FA886', '#2F4156', '#F4E3C8'],
    colors: { min: 2, max: 6, default: 6 },
    gridDefault: '8x12',
    freqDefault: 1,
    thumb: { grid: '5x5', frequency: 0.95 },
    vars: `--patch: @p(var(--color1), var(--color2), var(--color3), var(--color4)); --patch2: @p(var(--color1), var(--color2), var(--color3), var(--color4), var(--color5)); --cut: @p(polygon(0% 0%, 100% 0%, 100% 100%), polygon(0% 0%, 100% 0%, 0% 100%), polygon(0% 0%, 100% 100%, 0% 100%), polygon(100% 0%, 100% 100%, 0% 100%));`,
    rule: `@random(\${shapeFrequency}) { width: 94%; height: 94%; margin: 3%; background: var(--patch); :after { content: ''; position: absolute; inset: 0; background: var(--patch2); clip-path: var(--cut); transition: ease 500ms; } } transition: ease 500ms;`,
  },
  {
    name: 'Lantern',
    slug: 'lantern',
    order: 71,
    white: true,
    description:
      'Paper lanterns drifting in the night, each casting its own halo — reseeding floats them to new heights and re-mixes the glow.',
    palette: ['#181A2E', '#FFD27D', '#FF9E4D', '#FF5E62', '#E84393', '#B388EB'],
    colors: { min: 2, max: 6, default: 6 },
    gridDefault: '6x9',
    freqDefault: 0.9,
    thumb: { grid: '4x4', frequency: 0.85 },
    vars: `--ty: @rand(8%, 38%); --op: @rand(0.55, 1);`,
    rule: `/* lantern body and halo share one emitted color */ --glow: @p(var(--color1), var(--color2), var(--color3), var(--color4), var(--color5)); @random(\${shapeFrequency}) { :after { content: ''; position: absolute; left: 31%; top: var(--ty); width: 38%; height: 50%; border-radius: 30% / 24%; background: @var(--glow); box-shadow: 0 0 calc(300px / @Y) @var(--glow); opacity: var(--op); transition: ease 700ms; } }`,
  },
  {
    name: 'Domino',
    slug: 'domino',
    order: 73,
    description:
      'Two-tone tiles flipping between orientations like a table of dominoes mid-shuffle — halves trade colors as the tiles turn.',
    palette: ['#EFEFEA', '#2B4570', '#F6F1E7', '#D34E3A', '#E8B44F', '#4A7C59'],
    colors: { min: 2, max: 6, default: 6 },
    gridDefault: '8x12',
    freqDefault: 1,
    thumb: { grid: '5x5', frequency: 0.95 },
    vars: `--a: @p(var(--color1), var(--color2), var(--color3)); --b: @p(var(--color3), var(--color4), var(--color5)); --rot: @p(0deg, 90deg, 180deg, 270deg);`,
    rule: `@random(\${shapeFrequency}) { width: 86%; height: 86%; margin: 7%; background: var(--a); border-radius: 8%; transform: rotate(var(--rot)); :after { content: ''; position: absolute; left: 0; top: 50%; width: 100%; height: 50%; background: var(--b); border-radius: 0 0 10% 10%; transition: ease 500ms; } } transition: ease 500ms;`,
  },
  {
    name: 'Ivy',
    slug: 'ivy',
    order: 78,
    description:
      'Quarter-round leaves tiling into winding vines — each leaf swells from a different corner after every redraw.',
    palette: ['#F2F7EE', '#2F6B3C', '#4F9D5D', '#8CC084', '#C8E6C0'],
    colors: { min: 2, max: 5, default: 5 },
    gridDefault: '8x12',
    freqDefault: 1,
    thumb: { grid: '6x6', frequency: 0.95 },
    vars: `--leaf: @p(var(--color1), var(--color1), var(--color2), var(--color3), var(--color4)); --corner: @p(100% 0 0 0, 0 100% 0 0, 0 0 100% 0, 0 0 0 100%);`,
    rule: `@random(\${shapeFrequency}) { width: 96%; height: 96%; margin: 2%; background: var(--leaf); border-radius: var(--corner); } transition: ease 500ms;`,
  },
  {
    name: 'Neon',
    slug: 'neon',
    order: 80,
    white: true,
    description:
      'Glowing tube segments rearranging themselves on a dark wall — each redraw re-aims the lights and re-mixes their halos.',
    palette: ['#14101F', '#FF2E97', '#2EE6FF', '#B14EFF', '#45FFA2'],
    colors: { min: 2, max: 5, default: 5 },
    gridDefault: '6x9',
    freqDefault: 0.8,
    thumb: { grid: '5x5', frequency: 0.8 },
    vars: `--ang: @p(0deg, 45deg, 90deg, 135deg);`,
    rule: `/* tube and both halos share one emitted color */ --tube: @p(var(--color1), var(--color2), var(--color3), var(--color4)); @random(\${shapeFrequency}) { transform: rotate(var(--ang)); :after { content: ''; position: absolute; left: 14%; top: 47%; width: 72%; height: 6%; border-radius: 99px; background: @var(--tube); box-shadow: 0 0 calc(80px / @Y) @var(--tube), 0 0 calc(200px / @Y) @var(--tube); transition: ease 500ms; } } transition: ease 500ms;`,
  },
  {
    name: 'Bokeh',
    slug: 'bokeh',
    order: 81,
    white: true,
    description:
      'Out-of-focus city lights swimming in the dark — discs drift, swell and refocus softly with every redraw.',
    palette: ['#1A1626', '#FFC15E', '#FF8FA3', '#8AB6FF'],
    colors: { min: 2, max: 4, default: 2 },
    gridDefault: '6x9',
    freqDefault: 0.9,
    thumb: { grid: '4x4', frequency: 0.85 },
    vars: `--light: @p(var(--color1), var(--color2), var(--color3)); --d: @rand(26%, 88%); --lx: @rand(-10%, 60%); --ly: @rand(-10%, 60%); --lo: @rand(0.25, 0.9); --bl: @rand(1px, 6px);`,
    rule: `@random(\${shapeFrequency}) { :after { content: ''; position: absolute; @size: var(--d); left: var(--lx); top: var(--ly); border-radius: 50%; background: var(--light); opacity: var(--lo); filter: blur(var(--bl)); transition: ease 800ms; } }`,
  },
  {
    name: 'Shuffle',
    slug: 'shuffle',
    order: 88,
    description:
      'Pairs of rounded blocks sliding between the four corners of their frame — every redraw deals a new arrangement, like tiles in a pocket puzzle.',
    palette: ['#FFF8E8', '#FF6B6B', '#4ECDC4', '#FFD93D', '#6C5CE7', '#95E1D3'],
    colors: { min: 2, max: 6, default: 6 },
    gridDefault: '8x12',
    freqDefault: 1,
    thumb: { grid: '5x5', frequency: 0.9 },
    vars: `--q1x: @p(2%, 52%); --q1y: @p(2%, 52%); --q2x: @p(2%, 52%); --q2y: @p(2%, 52%); --blk1: @p(var(--color1), var(--color2), var(--color3)); --blk2: @p(var(--color3), var(--color4), var(--color5));`,
    rule: `@random(\${shapeFrequency}) { :before { content: ''; position: absolute; @size: 46%; left: var(--q1x); top: var(--q1y); border-radius: 14%; background: var(--blk1); transition: ease 500ms; } :after { content: ''; position: absolute; @size: 46%; left: var(--q2x); top: var(--q2y); border-radius: 14%; background: var(--blk2); opacity: 0.92; transition: ease 500ms; } }`,
  },
  {
    name: 'Aster',
    slug: 'aster',
    order: 91,
    description:
      'Six-armed thread stars twirling lazily across the canvas — every redraw spins each one to a new resting angle.',
    palette: ['#FFF8F2', '#FF7E9D', '#FFB35C', '#9D89F2', '#54C6B8'],
    colors: { min: 2, max: 5, default: 5 },
    options: [
      { kind: 'grid', default: '8x12' },
      {
        id: 'frequency',
        displayName: 'Frequency',
        type: 'Slider',
        default: 0.9,
        min: 0.2,
        max: 1,
        step: 0.1,
        replace: '${shapeFrequency}',
      },
      {
        id: 'thickness',
        displayName: 'Thickness',
        type: 'Slider',
        default: 1,
        min: 0.5,
        max: 4,
        step: 0.1,
        replace: '${thickness}',
      },
    ],
    thumb: { grid: '5x5', frequency: 0.9 },
    vars: `--spin: @rand(180deg);`,
    rule: `/* all three arms share one emitted color; thickness scales each arm along its own thin axis. The pseudo arms inherit the parent's scaleY, so they undo it before rotating to avoid shearing. */ --star: @p(var(--color1), var(--color2), var(--color3), var(--color4)); @random(\${shapeFrequency}) { width: 72%; height: 2.6%; margin: 48.7% 14%; border-radius: 99px; background: @var(--star); transform: rotate(var(--spin)) scaleY(\${thickness}); :before { content: ''; position: absolute; inset: 0; border-radius: 99px; background: @var(--star); transform: scaleY(calc(1 / \${thickness})) rotate(60deg) scaleY(\${thickness}); } :after { content: ''; position: absolute; inset: 0; border-radius: 99px; background: @var(--star); transform: scaleY(calc(1 / \${thickness})) rotate(120deg) scaleY(\${thickness}); } } transition: ease 600ms;`,
  },
];
