// Batch 2 (gallery orders 97-136).

export const batch2 = [
  {
    name: 'Aperture',
    slug: 'aperture',
    order: 105,
    white: true,
    description:
      'Camera irises dilating and stopping down across a dark contact sheet — ring thickness morphs between seeds like light being let in.',
    palette: ['#15171C', '#E8E6E1', '#F5B82E', '#3EECFF'],
    colors: { min: 2, max: 4, default: 2 },
    gridDefault: '8x12',
    freqDefault: 1,
    thumb: { grid: '5x5', frequency: 0.92 },
    vars: `--iris: @p(var(--color1), var(--color1), var(--color2), var(--color3));`,
    rule: `/* the aperture is a disc with a punched hole; the hole size morphs so the iris dilates */ @random(\${shapeFrequency}) { :before { content: ''; position: absolute; inset: 9%; border-radius: 50%; background: var(--iris); transition: ease 700ms; } :after { content: ''; position: absolute; inset: @rand(16%, 44%); border-radius: 50%; background: var(--color0); transition: ease 700ms; } }`,
  },
  {
    name: 'Argyle',
    slug: 'argyle',
    order: 109,
    description:
      'A lattice of lozenges whose vertices quiver from seed to seed — knitwear that never sits still.',
    palette: ['#F4EFE4', '#7A1F3D', '#2F4156', '#C9A86A'],
    colors: { min: 2, max: 4, default: 4 },
    gridDefault: '8x12',
    freqDefault: 1,
    thumb: { grid: '5x5', frequency: 0.95 },
    vars: `--lozenge: @p(var(--color1), var(--color2), var(--color3));`,
    rule: `/* each vertex jitters independently, so the lozenges quiver organically */ @random(\${shapeFrequency}) { background: var(--lozenge); clip-path: polygon(50% @rand(-6%, 10%), calc(100% - @rand(-6%, 10%)) 50%, 50% calc(100% - @rand(-6%, 10%)), @rand(-6%, 10%) 50%); } transition: ease 600ms;`,
  },
  {
    name: 'Bauhaus',
    slug: 'bauhaus',
    order: 114,
    description:
      'Circles, half-rounds, leaves and squares all cut from one border-radius — so every form morphs fluidly into the next on each redraw.',
    palette: ['#F2E9DC', '#E63329', '#1D3D8F', '#F0C02E', '#1A1A1A'],
    colors: { min: 2, max: 5, default: 5 },
    gridDefault: '8x12',
    freqDefault: 1,
    thumb: { grid: '5x5', frequency: 0.95 },
    vars: `/* every primitive is just a border-radius, so all of them interpolate */ --form: @p('50% 50% 50% 50%', '100% 100% 0% 0%', '0% 0% 100% 100%', '100% 0% 0% 100%', '0% 100% 100% 0%', '0% 0% 0% 0%', '100% 0% 100% 0%', '0% 100% 0% 100%'); --bold: @p(var(--color1), var(--color2), var(--color3), var(--color4));`,
    rule: `@random(\${shapeFrequency}) { background: var(--bold); border-radius: var(--form); } transition: ease 600ms;`,
  },
  {
    name: 'Halftone',
    slug: 'halftone',
    order: 116,
    description:
      'A halftone ramp printed top to bottom — dots grow with each row, and the whole screen shivers as every dot re-jitters per seed.',
    palette: ['#FAF7F0', '#232529', '#E6437D'],
    colors: { min: 2, max: 3, default: 2 },
    gridDefault: '10x15',
    freqDefault: 1,
    thumb: { grid: '7x7', frequency: 0.95 },
    vars: `--dot: @p(var(--color1), var(--color1), var(--color1), var(--color1), var(--color2));`,
    rule: `/* dot size ramps with the row, jittered by one emitted factor per cell */ --hd: calc((10 + 62 * @y / @Y) * @r(0.55, 1.25)); @random(\${shapeFrequency}) { :after { content: ''; position: absolute; @size: calc(@var(--hd) * 1%); left: calc(50% - @var(--hd) * 0.5%); top: calc(50% - @var(--hd) * 0.5%); border-radius: 50%; background: var(--dot); transition: ease 600ms; } }`,
  },
  {
    name: 'Elbow',
    slug: 'elbow',
    order: 120,
    description:
      'Fat pastel pipe elbows re-plumbing themselves quarter-turn by quarter-turn — the network reroutes on every redraw.',
    palette: ['#FBF6EF', '#FF8AAE', '#7EC8E3', '#FFC75F', '#9D89F2'],
    colors: { min: 2, max: 5, default: 5 },
    gridDefault: '8x12',
    freqDefault: 1,
    thumb: { grid: '5x5', frequency: 0.92 },
    vars: `--pipe: @p(var(--color1), var(--color2), var(--color3), var(--color4)); --bend: @p(0deg, 90deg, 180deg, 270deg);`,
    rule: `@random(\${shapeFrequency}) { :after { content: ''; position: absolute; inset: 0; border: solid var(--pipe); border-width: calc(170px / @Y) calc(170px / @Y) 0 0; border-radius: 0 100% 0 0; transform: rotate(var(--bend)); box-sizing: border-box; transition: ease 600ms; } }`,
  },
  {
    name: 'Grain',
    slug: 'grain',
    order: 127,
    white: true,
    description:
      'Silver film grain breathing in the dark — every cell fades to its own new exposure, slowly, like static settling.',
    palette: ['#0F0F10', '#E8E6E1', '#E63946'],
    colors: { min: 2, max: 3, default: 2 },
    gridDefault: '10x15',
    freqDefault: 1,
    thumb: { grid: '8x8', frequency: 0.95 },
    vars: `--g1: @rand(0.04, 0.8); --g2: @p(0%, 0%, 0%, 50%);`,
    rule: `@random(\${shapeFrequency}) { margin: 1px; background: var(--color1); opacity: var(--g1); border-radius: var(--g2); } @random(0.03) { background: var(--color2); opacity: 0.9; } transition: ease 900ms;`,
  },
  {
    name: 'Misprint',
    slug: 'misprint',
    order: 128,
    description:
      'Two riso plates sliding in and out of register — mirrored offsets pull the inks apart and let them overlap into new blends.',
    palette: ['#FBF7EE', '#FF4D6D', '#2E86AB', '#F5B82E', '#7E4A8C'],
    colors: { min: 2, max: 5, default: 5 },
    gridDefault: '6x9',
    freqDefault: 0.9,
    thumb: { grid: '4x4', frequency: 0.92 },
    vars: `--plate1: @p(var(--color1), var(--color3)); --plate2: @p(var(--color2), var(--color4));`,
    rule: `/* the two plates share one emitted offset, mirrored, so they slide apart symmetrically */ --mx: @r(-10, 10); --my: @r(-10, 10); @random(\${shapeFrequency}) { :before { content: ''; position: absolute; @size: 58%; left: calc(21% + @var(--mx) * 1%); top: calc(21% + @var(--my) * 1%); border-radius: 50%; background: var(--plate1); opacity: 0.72; mix-blend-mode: multiply; transition: ease 700ms; } :after { content: ''; position: absolute; @size: 58%; left: calc(21% - @var(--mx) * 1%); top: calc(21% - @var(--my) * 1%); border-radius: 50%; background: var(--plate2); opacity: 0.72; mix-blend-mode: multiply; transition: ease 700ms; } }`,
  },
  {
    name: 'Zipper',
    slug: 'zipper',
    order: 135,
    description:
      'Rows of rounded teeth meshing from alternate sides — the zip opens and closes a little differently on every redraw.',
    palette: ['#F4EFE6', '#2F4156', '#E2543E', '#F5B82E', '#2BB3A3'],
    colors: { min: 2, max: 5, default: 5 },
    gridDefault: '8x12',
    freqDefault: 1,
    thumb: { grid: '6x6', frequency: 0.95 },
    vars: `--toothA: @p(var(--color1), var(--color1), var(--color2), var(--color3)); --zw: @rand(42%, 80%);`,
    rule: `--zg: @r(0, 9); @random(\${shapeFrequency}) { :after { content: ''; position: absolute; left: 0; top: calc(16% + @var(--zg) * 1%); width: var(--zw); height: calc(68% - @var(--zg) * 2%); background: var(--toothA); border-radius: 0 26% 26% 0; transition: ease 600ms; } } @match(y % 2 == 0) { :after { left: auto; right: 0; border-radius: 26% 0 0 26%; } }`,
  },
];
