// Generates the site's agent-facing docs into public/ from the package's
// catalog.json (itself generated by packages/tabbied/scripts/codegen.mjs).
//
// Three files, in increasing depth, so a tool can stop as soon as it has
// enough:
//
//   /llms.txt       the llms.txt convention (llmstxt.org): a short index that
//                   links to everything else.
//   /llms-full.txt  the whole API contract plus a one-line entry for all 222
//                   designs — enough to pick a design and wire it up from a
//                   single fetch.
//   /catalog.json   the full structured catalog, for precise lookup of one
//                   design's options, palette, and export support.
//
// The point of all this is design discovery. The API is small enough to
// memorize, but the 222 slugs are opaque ("cleat", "gnomonwedge", "karst"), so
// an assistant with no catalog either guesses a slug that doesn't exist or
// imports the whole record and loses tree-shaking. The descriptions authored
// in artworks/*.json are what make the set searchable.
//
// Run via `npm run llms` (part of prebuild/predev, after the package build).
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const catalogPath = path.join(
  repoRoot,
  'packages',
  'tabbied',
  'catalog.json'
);
const publicDir = path.join(repoRoot, 'public');

const SITE = 'https://tabbied.com';
const REPO = 'https://github.com/subwaymatch/tabbied';

let catalog;
try {
  catalog = JSON.parse(await readFile(catalogPath, 'utf-8'));
} catch (error) {
  throw new Error(
    `generate-llms: could not read ${path.relative(repoRoot, catalogPath)}. ` +
      'Run `npm run build --workspace tabbied` first.',
    { cause: error }
  );
}

const { designs, count, version } = catalog;

// ---- /llms.txt -------------------------------------------------------------
// Per llmstxt.org: an H1, a blockquote summary, optional prose, then
// H2-delimited lists of links. "Optional" is the section a tool may skip when
// it's short on context.

const llms = `# Tabbied

> Generative artworks as data: ${count} preset designs powered by css-doodle, shipped as the \`tabbied\` npm package (v${version}) — a framework-agnostic core plus an optional React component. Render any design at any size, reseed it, and export to PNG or true vector SVG.

Install with \`npm install tabbied\`. React is an optional peer dependency, needed only for the \`tabbied/react\` entry point.

Designs are referred to by slug and imported individually — \`import { radius } from 'tabbied/artworks'\` — so a bundler ships only what you use. Slugs are lowercase alphanumeric and are not guessable from a description: read the catalog below to choose one.

## Docs

- [llms-full.txt](${SITE}/llms-full.txt): the complete API contract and a one-line entry for every design. Start here — it is designed to be enough on its own.
- [catalog.json](${SITE}/catalog.json): every design with its description, palette, options, default fit, and SVG-export support. Use it to look up one design in detail. Also shipped in the package at \`tabbied/catalog.json\`.
- [React component reference](${SITE}/docs/react/): props, sizing, and live examples.
- [Package README](${REPO}/blob/main/packages/tabbied/README.md): entry points, the core API, and SVG export.
- [SVG export notes](${REPO}/blob/main/docs/svg-export.md): what the vector exporter supports and where it degrades.

## Optional

- [Tabbied](${SITE}): browse, customize, and export the designs in the browser.
- [Repository](${REPO})
`;

// ---- /llms-full.txt --------------------------------------------------------

// Anything that makes generated code compile but render wrong belongs here —
// that's what a model can't infer from the type signatures.
const apiReference = `# Tabbied — full reference for LLMs

> Generated from tabbied v${version}. ${count} designs. Canonical index: ${SITE}/llms.txt

## Install

\`\`\`bash
npm install tabbied
\`\`\`

React is an **optional** peer dependency (>=18 <20), needed only for
\`tabbied/react\`. The core runs in any framework, or none. Node >=18.

## Entry points

| Import | Provides |
| --- | --- |
| \`tabbied\` | Framework-agnostic core: \`createArtwork\`, sizing/seed helpers, types. |
| \`tabbied/react\` | The \`TabbiedArtwork\` component and its handle/prop types. |
| \`tabbied/artworks\` | The presets. Import individually; the \`artworks\` record holds all ${count}. |
| \`tabbied/svg-export\` | \`doodleToSvg\`, the vector converter, for use on a doodle you manage. |
| \`tabbied/catalog.json\` | This catalog as data. |

## React

\`\`\`tsx
import { TabbiedArtwork, type TabbiedArtworkHandle } from 'tabbied/react';
import { radius } from 'tabbied/artworks';
import { useRef } from 'react';

export function Example() {
  const ref = useRef<TabbiedArtworkHandle>(null);

  return (
    <>
      <TabbiedArtwork ref={ref} artwork={radius} seed="k9Pz" height={320} />
      <button onClick={() => ref.current?.redraw()}>Redraw</button>
      <button onClick={() => ref.current?.exportImage()}>Export PNG</button>
      <button onClick={() => ref.current?.exportSvg({ download: true })}>
        Export SVG
      </button>
    </>
  );
}
\`\`\`

### Props

| Prop | Description |
| --- | --- |
| \`artwork\` | An \`ArtworkDefinition\` — a preset from \`tabbied/artworks\`, or your own. Required. |
| \`seed\` | Pattern seed. Omit for a random seed per mount; reseed via the handle. |
| \`palette\` | Active colors, background (\`color0\`) first. Defaults to the preset palette. |
| \`options\` | Option values keyed by option id. Unset options use their authored default. |
| \`fit\` | \`grid\`, \`cover\`, \`contain\`, or \`fixed\`. Optional — each design declares its own default (\`fit.default\` in the catalog). |
| \`fill\` | \`width: 100%; height: 100%\`. Defaults to \`true\`. |
| \`width\` / \`height\` | Box size. Numbers are px. Overrides \`fill\` on that axis. |
| \`maxWidth\` / \`maxHeight\` | Upper bounds on the box. |
| \`aspectRatio\` | CSS \`aspect-ratio\`, e.g. \`3 / 2\`. Derives height from width. |
| \`coverRender\` | Render resolution for the \`cover\`/\`contain\` fits (default 800x800). |
| \`redrawInterval\` | Re-randomize the seed every N ms. Off under \`prefers-reduced-motion\`; ticks drop while the tab is hidden or the box is off-screen. |
| \`paused\` | Pause \`redrawInterval\` ticks. No effect unless \`redrawInterval\` is set. |
| \`onReady\` | Fires once the artwork has been measured and first painted. |

The handle (\`TabbiedArtworkHandle\`) exposes \`redraw(seed?)\`,
\`exportImage(options?)\`, \`exportSvg(options?)\`, and \`element\` — the raw
\`<css-doodle>\` node.

## Sizing

An artwork has no intrinsic size — it takes the size of the box you give it.
By default that box fills its containing block.

\`\`\`tsx
// Fill a sized parent.
<div style={{ height: 400 }}><TabbiedArtwork artwork={radius} /></div>

// Cap the width and let the ratio set the height.
<TabbiedArtwork artwork={radius} maxWidth={960} aspectRatio={3 / 2} />

// Full-bleed banner.
<TabbiedArtwork artwork={radius} height="40vh" />
\`\`\`

**Gotchas that compile but render wrong:**

- \`height: 100%\` (which \`fill\` sets) only resolves against a parent with a
  **definite height**. In a parent that sizes to its content the artwork
  collapses — pass \`height\` or \`aspectRatio\` instead.
- The React component is a **client component** (it registers a browser custom
  element on import). In the Next.js App Router, render it from a client
  boundary or rely on its built-in placeholder until it mounts.
- Measured fits (\`grid\`, \`cover\`, \`contain\`) mount **asynchronously**, after
  the first ResizeObserver tick. With the core API, drive the controller from
  \`onReady\`, not immediately after \`createArtwork()\`.
- Requesting a fit an artwork can't support falls back to its default and warns.
- In a CSS grid, give tracks \`minmax(0, 1fr)\` rather than \`1fr\` so they can
  shrink when the container narrows.

### Fit modes

No fit distorts the artwork — nothing is ever scaled by a different factor
horizontally than vertically.

- \`grid\` (default for designs with a grid option) — re-derives the cell grid
  from the measured box, so cells stay near-square at any box shape.
- \`cover\` — draws at a fixed resolution and scales it uniformly to fill the
  box, preserving the proportions of fixed-px strokes and shadows.
- \`contain\` — letterboxes that fixed-resolution render at its authored ratio.
- \`fixed\` — renders at an explicit canvas size (default 360x540).

\`fit="stretch"\` was **removed in 0.2.0**. Use \`grid\` or \`cover\`.

## Palettes and options

\`palette\` is an array of CSS colors with the **background first** (\`color0\`);
the rest are the inks. Each design declares \`colors: { min, max, default }\`
bounds; the catalog lists the authored palette for every design.

\`options\` is keyed by option id, and each design declares its own. Three
control types: \`ButtonSelectGroup\` (one of \`values\`), \`Slider\` (a number
within \`min\`/\`max\`), and \`ToggleSwitch\` (a boolean).

\`\`\`tsx
<TabbiedArtwork
  artwork={radius}
  palette={['#0B1020', '#3E8BFF', '#3FFFB2']}
  options={{ grid: '8x12', frequency: 0.6, shadow: true }}
/>
\`\`\`

## Core (framework-agnostic)

\`\`\`ts
import { createArtwork } from 'tabbied';
import { radius } from 'tabbied/artworks';

const controller = createArtwork(document.querySelector('#stage'), {
  artwork: radius,
  seed: 'k9Pz',
  onReady: async () => {
    controller.redraw();
    await controller.exportImage();
    const { svg } = await controller.exportSvg();
  },
});

// later: controller.destroy();
\`\`\`

The controller takes the same config the component takes as props (minus the
box props — the host element is yours to size, or run them through
\`resolveBoxStyle()\`). That includes \`redrawInterval\` and \`paused\`: the timer
and its reduced-motion, tab-visibility and viewport gates live in the
controller, so the vanilla API animates without reimplementing them.

\`\`\`js
const controller = createArtwork(host, {
  artwork: radius,
  redrawInterval: 5200,
});
controller.update({ paused: true }); // holds the phase; resume with false
\`\`\`

## SVG export

\`exportSvg()\` produces a **native vector SVG** (real \`<rect>\`/\`<path>\`/gradient
elements, no \`<foreignObject>\`), resolving with
\`{ svg, width, height, warnings }\`. Pass \`{ download: true }\` to save a file.
The converter (~21 KB gzipped) is loaded on demand, so apps that never export
pay nothing.

Call \`supportsSvgExport(artwork)\` before offering the option: ${
  designs.filter((design) => !design.svgExport.supported).length
} designs paint
smooth conic sweeps that SVG cannot represent and are marked unsupported below.
Designs with partial limitations carry a note (filter-based effects that
browsers render correctly but design tools may import imperfectly); surface
those to the user before downloading. Unsupported CSS throws
\`SvgExportUnsupportedError\` rather than emitting a wrong file.

## Designs

${count} presets. Import by slug from \`tabbied/artworks\`:
\`import { <slug> } from 'tabbied/artworks'\`. Options, palettes, and per-design
detail are in ${SITE}/catalog.json.

Legend: \`[no SVG]\` cannot export to SVG; \`[SVG note]\` exports with a
documented limitation.
`;

const designLine = (design) => {
  const flags = [];
  if (!design.svgExport.supported) flags.push('[no SVG]');
  else if (
    design.svgExport.note ||
    design.options.some((option) => option.svgExportNote)
  ) {
    flags.push('[SVG note]');
  }

  const description = design.description ?? `The ${design.name} design.`;
  const suffix = flags.length ? ` ${flags.join(' ')}` : '';

  return `- \`${design.slug}\` — ${design.name}. ${description}${suffix}`;
};

const llmsFull = `${apiReference}
${designs.map(designLine).join('\n')}
`;

await mkdir(publicDir, { recursive: true });

await Promise.all([
  writeFile(path.join(publicDir, 'llms.txt'), llms),
  writeFile(path.join(publicDir, 'llms-full.txt'), llmsFull),
  // Served alongside so a tool can fetch the structured form directly.
  writeFile(
    path.join(publicDir, 'catalog.json'),
    `${JSON.stringify(catalog, null, 2)}\n`
  ),
]);

const kb = (text) => `${Math.round(Buffer.byteLength(text) / 102.4) / 10} KB`;

console.log(
  `generate-llms: wrote public/llms.txt (${kb(llms)}), ` +
    `public/llms-full.txt (${kb(llmsFull)}), and public/catalog.json ` +
    `for ${count} designs`
);
